// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetHouses.proto

package GetHouses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetHouses service

func NewGetHousesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetHouses service

type GetHousesService interface {
	GetHouses(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetHouses_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (GetHouses_PingPongService, error)
}

type getHousesService struct {
	c    client.Client
	name string
}

func NewGetHousesService(name string, c client.Client) GetHousesService {
	return &getHousesService{
		c:    c,
		name: name,
	}
}

func (c *getHousesService) GetHouses(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetHouses.GetHouses", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getHousesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetHouses_StreamService, error) {
	req := c.c.NewRequest(c.name, "GetHouses.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getHousesServiceStream{stream}, nil
}

type GetHouses_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type getHousesServiceStream struct {
	stream client.Stream
}

func (x *getHousesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *getHousesServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getHousesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getHousesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getHousesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getHousesService) PingPong(ctx context.Context, opts ...client.CallOption) (GetHouses_PingPongService, error) {
	req := c.c.NewRequest(c.name, "GetHouses.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getHousesServicePingPong{stream}, nil
}

type GetHouses_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type getHousesServicePingPong struct {
	stream client.Stream
}

func (x *getHousesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *getHousesServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *getHousesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getHousesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getHousesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *getHousesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetHouses service

type GetHousesHandler interface {
	GetHouses(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, GetHouses_StreamStream) error
	PingPong(context.Context, GetHouses_PingPongStream) error
}

func RegisterGetHousesHandler(s server.Server, hdlr GetHousesHandler, opts ...server.HandlerOption) error {
	type getHouses interface {
		GetHouses(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type GetHouses struct {
		getHouses
	}
	h := &getHousesHandler{hdlr}
	return s.Handle(s.NewHandler(&GetHouses{h}, opts...))
}

type getHousesHandler struct {
	GetHousesHandler
}

func (h *getHousesHandler) GetHouses(ctx context.Context, in *Request, out *Response) error {
	return h.GetHousesHandler.GetHouses(ctx, in, out)
}

func (h *getHousesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetHousesHandler.Stream(ctx, m, &getHousesStreamStream{stream})
}

type GetHouses_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type getHousesStreamStream struct {
	stream server.Stream
}

func (x *getHousesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getHousesStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getHousesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getHousesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getHousesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *getHousesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GetHousesHandler.PingPong(ctx, &getHousesPingPongStream{stream})
}

type GetHouses_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type getHousesPingPongStream struct {
	stream server.Stream
}

func (x *getHousesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *getHousesPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getHousesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getHousesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getHousesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *getHousesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
