// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/PostLogin.proto

package PostLogin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PostLogin service

func NewPostLoginEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PostLogin service

type PostLoginService interface {
	PostLogin(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PostLogin_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (PostLogin_PingPongService, error)
}

type postLoginService struct {
	c    client.Client
	name string
}

func NewPostLoginService(name string, c client.Client) PostLoginService {
	return &postLoginService{
		c:    c,
		name: name,
	}
}

func (c *postLoginService) PostLogin(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostLogin.PostLogin", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postLoginService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PostLogin_StreamService, error) {
	req := c.c.NewRequest(c.name, "PostLogin.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postLoginServiceStream{stream}, nil
}

type PostLogin_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postLoginServiceStream struct {
	stream client.Stream
}

func (x *postLoginServiceStream) Close() error {
	return x.stream.Close()
}

func (x *postLoginServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postLoginServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postLoginServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postLoginServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postLoginService) PingPong(ctx context.Context, opts ...client.CallOption) (PostLogin_PingPongService, error) {
	req := c.c.NewRequest(c.name, "PostLogin.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postLoginServicePingPong{stream}, nil
}

type PostLogin_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postLoginServicePingPong struct {
	stream client.Stream
}

func (x *postLoginServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *postLoginServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *postLoginServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postLoginServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postLoginServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postLoginServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PostLogin service

type PostLoginHandler interface {
	PostLogin(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, PostLogin_StreamStream) error
	PingPong(context.Context, PostLogin_PingPongStream) error
}

func RegisterPostLoginHandler(s server.Server, hdlr PostLoginHandler, opts ...server.HandlerOption) error {
	type postLogin interface {
		PostLogin(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type PostLogin struct {
		postLogin
	}
	h := &postLoginHandler{hdlr}
	return s.Handle(s.NewHandler(&PostLogin{h}, opts...))
}

type postLoginHandler struct {
	PostLoginHandler
}

func (h *postLoginHandler) PostLogin(ctx context.Context, in *Request, out *Response) error {
	return h.PostLoginHandler.PostLogin(ctx, in, out)
}

func (h *postLoginHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostLoginHandler.Stream(ctx, m, &postLoginStreamStream{stream})
}

type PostLogin_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postLoginStreamStream struct {
	stream server.Stream
}

func (x *postLoginStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postLoginStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postLoginStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postLoginStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postLoginStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *postLoginHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PostLoginHandler.PingPong(ctx, &postLoginPingPongStream{stream})
}

type PostLogin_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postLoginPingPongStream struct {
	stream server.Stream
}

func (x *postLoginPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postLoginPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postLoginPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postLoginPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postLoginPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postLoginPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
