// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/PostUserAuth.proto

package PostUserAuth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PostUserAuth service

func NewPostUserAuthEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PostUserAuth service

type PostUserAuthService interface {
	PostUserAuth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PostUserAuth_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (PostUserAuth_PingPongService, error)
}

type postUserAuthService struct {
	c    client.Client
	name string
}

func NewPostUserAuthService(name string, c client.Client) PostUserAuthService {
	return &postUserAuthService{
		c:    c,
		name: name,
	}
}

func (c *postUserAuthService) PostUserAuth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostUserAuth.PostUserAuth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postUserAuthService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PostUserAuth_StreamService, error) {
	req := c.c.NewRequest(c.name, "PostUserAuth.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postUserAuthServiceStream{stream}, nil
}

type PostUserAuth_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postUserAuthServiceStream struct {
	stream client.Stream
}

func (x *postUserAuthServiceStream) Close() error {
	return x.stream.Close()
}

func (x *postUserAuthServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postUserAuthServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postUserAuthServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postUserAuthServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postUserAuthService) PingPong(ctx context.Context, opts ...client.CallOption) (PostUserAuth_PingPongService, error) {
	req := c.c.NewRequest(c.name, "PostUserAuth.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postUserAuthServicePingPong{stream}, nil
}

type PostUserAuth_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postUserAuthServicePingPong struct {
	stream client.Stream
}

func (x *postUserAuthServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *postUserAuthServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *postUserAuthServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postUserAuthServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postUserAuthServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postUserAuthServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PostUserAuth service

type PostUserAuthHandler interface {
	PostUserAuth(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, PostUserAuth_StreamStream) error
	PingPong(context.Context, PostUserAuth_PingPongStream) error
}

func RegisterPostUserAuthHandler(s server.Server, hdlr PostUserAuthHandler, opts ...server.HandlerOption) error {
	type postUserAuth interface {
		PostUserAuth(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type PostUserAuth struct {
		postUserAuth
	}
	h := &postUserAuthHandler{hdlr}
	return s.Handle(s.NewHandler(&PostUserAuth{h}, opts...))
}

type postUserAuthHandler struct {
	PostUserAuthHandler
}

func (h *postUserAuthHandler) PostUserAuth(ctx context.Context, in *Request, out *Response) error {
	return h.PostUserAuthHandler.PostUserAuth(ctx, in, out)
}

func (h *postUserAuthHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostUserAuthHandler.Stream(ctx, m, &postUserAuthStreamStream{stream})
}

type PostUserAuth_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postUserAuthStreamStream struct {
	stream server.Stream
}

func (x *postUserAuthStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postUserAuthStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postUserAuthStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postUserAuthStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postUserAuthStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *postUserAuthHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PostUserAuthHandler.PingPong(ctx, &postUserAuthPingPongStream{stream})
}

type PostUserAuth_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postUserAuthPingPongStream struct {
	stream server.Stream
}

func (x *postUserAuthPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postUserAuthPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postUserAuthPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postUserAuthPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postUserAuthPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postUserAuthPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
