// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetIndex.proto

package GetIndex

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetIndex service

func NewGetIndexEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetIndex service

type GetIndexService interface {
	GetIndex(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetIndex_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (GetIndex_PingPongService, error)
}

type getIndexService struct {
	c    client.Client
	name string
}

func NewGetIndexService(name string, c client.Client) GetIndexService {
	return &getIndexService{
		c:    c,
		name: name,
	}
}

func (c *getIndexService) GetIndex(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetIndex.GetIndex", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getIndexService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetIndex_StreamService, error) {
	req := c.c.NewRequest(c.name, "GetIndex.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getIndexServiceStream{stream}, nil
}

type GetIndex_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type getIndexServiceStream struct {
	stream client.Stream
}

func (x *getIndexServiceStream) Close() error {
	return x.stream.Close()
}

func (x *getIndexServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getIndexServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getIndexServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getIndexServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getIndexService) PingPong(ctx context.Context, opts ...client.CallOption) (GetIndex_PingPongService, error) {
	req := c.c.NewRequest(c.name, "GetIndex.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getIndexServicePingPong{stream}, nil
}

type GetIndex_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type getIndexServicePingPong struct {
	stream client.Stream
}

func (x *getIndexServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *getIndexServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *getIndexServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getIndexServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getIndexServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *getIndexServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetIndex service

type GetIndexHandler interface {
	GetIndex(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, GetIndex_StreamStream) error
	PingPong(context.Context, GetIndex_PingPongStream) error
}

func RegisterGetIndexHandler(s server.Server, hdlr GetIndexHandler, opts ...server.HandlerOption) error {
	type getIndex interface {
		GetIndex(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type GetIndex struct {
		getIndex
	}
	h := &getIndexHandler{hdlr}
	return s.Handle(s.NewHandler(&GetIndex{h}, opts...))
}

type getIndexHandler struct {
	GetIndexHandler
}

func (h *getIndexHandler) GetIndex(ctx context.Context, in *Request, out *Response) error {
	return h.GetIndexHandler.GetIndex(ctx, in, out)
}

func (h *getIndexHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetIndexHandler.Stream(ctx, m, &getIndexStreamStream{stream})
}

type GetIndex_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type getIndexStreamStream struct {
	stream server.Stream
}

func (x *getIndexStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getIndexStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getIndexStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getIndexStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getIndexStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *getIndexHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GetIndexHandler.PingPong(ctx, &getIndexPingPongStream{stream})
}

type GetIndex_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type getIndexPingPongStream struct {
	stream server.Stream
}

func (x *getIndexPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *getIndexPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getIndexPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getIndexPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getIndexPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *getIndexPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
