// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/PutComment.proto

package PutComment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PutComment service

func NewPutCommentEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PutComment service

type PutCommentService interface {
	PutComment(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PutComment_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (PutComment_PingPongService, error)
}

type putCommentService struct {
	c    client.Client
	name string
}

func NewPutCommentService(name string, c client.Client) PutCommentService {
	return &putCommentService{
		c:    c,
		name: name,
	}
}

func (c *putCommentService) PutComment(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PutComment.PutComment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *putCommentService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PutComment_StreamService, error) {
	req := c.c.NewRequest(c.name, "PutComment.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &putCommentServiceStream{stream}, nil
}

type PutComment_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type putCommentServiceStream struct {
	stream client.Stream
}

func (x *putCommentServiceStream) Close() error {
	return x.stream.Close()
}

func (x *putCommentServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putCommentServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putCommentServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putCommentServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *putCommentService) PingPong(ctx context.Context, opts ...client.CallOption) (PutComment_PingPongService, error) {
	req := c.c.NewRequest(c.name, "PutComment.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &putCommentServicePingPong{stream}, nil
}

type PutComment_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type putCommentServicePingPong struct {
	stream client.Stream
}

func (x *putCommentServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *putCommentServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *putCommentServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putCommentServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putCommentServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *putCommentServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PutComment service

type PutCommentHandler interface {
	PutComment(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, PutComment_StreamStream) error
	PingPong(context.Context, PutComment_PingPongStream) error
}

func RegisterPutCommentHandler(s server.Server, hdlr PutCommentHandler, opts ...server.HandlerOption) error {
	type putComment interface {
		PutComment(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type PutComment struct {
		putComment
	}
	h := &putCommentHandler{hdlr}
	return s.Handle(s.NewHandler(&PutComment{h}, opts...))
}

type putCommentHandler struct {
	PutCommentHandler
}

func (h *putCommentHandler) PutComment(ctx context.Context, in *Request, out *Response) error {
	return h.PutCommentHandler.PutComment(ctx, in, out)
}

func (h *putCommentHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PutCommentHandler.Stream(ctx, m, &putCommentStreamStream{stream})
}

type PutComment_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type putCommentStreamStream struct {
	stream server.Stream
}

func (x *putCommentStreamStream) Close() error {
	return x.stream.Close()
}

func (x *putCommentStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putCommentStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putCommentStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putCommentStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *putCommentHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PutCommentHandler.PingPong(ctx, &putCommentPingPongStream{stream})
}

type PutComment_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type putCommentPingPongStream struct {
	stream server.Stream
}

func (x *putCommentPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *putCommentPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putCommentPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putCommentPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putCommentPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *putCommentPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
